### ISSUE TITLE
HW Git 

### ISSUE THREAD

**Issue by AliakseiShvants** [AliakseiShvants/RunningLife#1]
@ajaxspace https://github.com/AliakseiShvants/RunningLife/compare/94947be649636f2931db27d5aac54c423d4290ea...717c848f3940ea7ac09f97dd8c052088d43657dc

**Comment by AliakseiShvants** [comment]
new compare link https://github.com/AliakseiShvants/RunningLife/compare/717c848...aedc160d6e1433a46ecbeaf5fd6dbc2ff29bab20

**Comment by ajaxspace** [comment]
Please create issue in https://github.com/DzmitrySlutskiy/EpamTraining2019 repository so I can close it  if it is completed.
